### ISSUE TITLE
Modularize Page method

### ISSUE THREAD

**Issue by jondashkyle** [enokidotsite/enoki#15]
Enoki exposes a handy `Page` method for easily traversing `content` state as generated with `hypha`. It’s used like this:

```js
var Page = require('enoki/page')
```

While we should keep that around, it could be useful to break this out into it’s own module, especially as the core `enoki` module grows with the incoming static output of `content` state to `JSON`, as that’s going to include some heavier deps like `watch`. Think of this similarly to how Choo exposes nanohtml (bel) via `require('choo/html')`. Helps to keep things focused and small.

Could also be nice to refactor how this is structured a little, just some basic clean up.

@jongacnik

**Comment by jongacnik** [comment]
Just wanted to add a note from our call here to potentially use top level keys to identify children. Let's say our content object looks like:

```js
{
  '/projects': {},
  '/projects/a': {},
  '/projects/b': {},
  '/projects/c': {}
}
```

Calling `page('/projects').children()` could return `/projects/a, /projects/b, /projects/c` since they share the same prefix. This may allow us to keep our content a little more concise, instead of the current:

```js
{
  '/projects': {
    pages: {
      '/projects/a': {},
      '/projects/b': {},
      '/projects/c': {}
    }
  },
  '/projects/a': {},
  '/projects/b': {},
  '/projects/c': {}
}
```

Jumping into a new build tomorrow, if it's helpful, I could scaffold this flat structure, while also thinking about some cleanup.

**Comment by jondashkyle** [comment]
Sounds awesome, feel free to scaffold and we can work it in via a pull request! Down to integrate this first, then follow up with the `gr8`-esque utilities extensibility, then publish as a standalone module.

**Comment by jondashkyle** [comment]
https://github.com/enokidotsite/enoki/pull/17
